### ISSUE TITLE
Upgraded enforcers aren't running on application/compute nodes

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#167]
Updated enforcer pods are crashing on infrastructure nodes; 

```

INFO	Validating enforcer identity and uniqueuness ...
--
  | INFO	Update check enabled	{"currentVersion": "v1.901.12"}
  | ERROR	Unable to initialize optional component auditor	{"error": "unable to configure backlog limit in the kernel: operation not permitted"}
  | ERROR	unable to delete chain	{"table": "nat", "chain": "TRI-Redir-App", "error": "running [/sbin/iptables -t nat -X TRI-Redir-App --wait]: exit status 1: iptables: Too many links.\n"}
  | ERROR	unable to delete chain	{"table": "nat", "chain": "TRI-Redir-Net", "error": "running [/sbin/iptables -t nat -X TRI-Redir-Net --wait]: exit status 1: iptables: Too many links.\n"}
  | ERROR	Error when starting the supervisor	{"error": "unable to start the implementer: Unable to initialize chains: running [/sbin/iptables -t nat -N TRI-Redir-App --wait]: exit status 1: iptables: Chain already exists.\n"}
  | FATAL	Unable to start controllers	{"error": "Failed to activate controler: Error while starting supervisor unable to start the implementer: Unable to initialize chains: running [/sbin/iptables -t nat -N TRI-Redir-App --wait]: exit status 1: iptables: Chain already exists.\n"}

```

A list of the nodes affected: 

```
[sheastewart@sheawei platform-services]$ oc get pods -o wide 
NAME                                READY     STATUS             RESTARTS   AGE       IP              NODE               NOMINATED NODE
aporeto-operator-6798cc547b-5jvfh   1/1       Running            0          23h       10.131.27.159   ociopf-t-334.dmz   <none>
enforcerd-9wxvn                     1/1       Running            0          34m       142.34.217.52   ociopf-t-312.dmz   <none>
enforcerd-ncmn7                     0/1       CrashLoopBackOff   6          17m       142.34.217.54   ociopf-t-321.dmz   <none>
enforcerd-p72mc                     0/1       CrashLoopBackOff   6          18m       142.34.217.55   ociopf-t-322.dmz   <none>
enforcerd-p8szz                     1/1       Running            0          33m       142.34.217.53   ociopf-t-313.dmz   <none>
enforcerd-qgfhp                     1/1       Running            0          34m       142.34.217.51   ociopf-t-311.dmz   <none>
```

**Comment by mheese** [comment]
@stewartshea this is still an ongoing problem on our end ... digging into this now myself

**Comment by stewartshea** [comment]
@mheese logs from the crashing enforcer (from the custom image)

```

__                            _
--
  | ___ _ __  / _\| ___  _ __ ___ ___ _ __ __\| \|
  | / _ \ '_ \\| \|_ / _ \\| '__/ __/ _ \ '__/ _' \|
  | \|  __/ \| \| \|  _\| (_) \| \| \| (_\|  __/ \| \| (_\| \|
  | \___\|_\| \|_\|_\|  \___/\|_\|  \___\___\|_\|  \__,_\|
  |  
  | Aporeto Enforcer Agent
  | v0.0.0-dev - e0314805b691516aea6c6e956aae22a520820f25
  | _______________________________________________________________
  |  
  | ERROR	Unable to initialize ipv6 iptables :%s	{"error": "exec: \"ip6tables\": executable file not found in $PATH"}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D PREROUTING -p tcp -m addrtype --dst-type LOCAL -m set ! --match-set TRI-v4-Excluded src -j TRI-Redir-Net --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "PREROUTING", "cr[2:]": ["-p", "tcp", "-m", "addrtype", "--dst-type", "LOCAL", "-m", "set", "!", "--match-set", "TRI-v4-Excluded", "src", "-j", "TRI-Redir-Net"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D PREROUTING -p tcp -m addrtype --dst-type LOCAL -m set ! --match-set TRI-v4-Excluded src -j TRI-Redir-Net --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "PREROUTING", "cr[2:]": ["-p", "tcp", "-m", "addrtype", "--dst-type", "LOCAL", "-m", "set", "!", "--match-set", "TRI-v4-Excluded", "src", "-j", "TRI-Redir-Net"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D PREROUTING -p tcp -m addrtype --dst-type LOCAL -m set ! --match-set TRI-v4-Excluded src -j TRI-Redir-Net --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "PREROUTING", "cr[2:]": ["-p", "tcp", "-m", "addrtype", "--dst-type", "LOCAL", "-m", "set", "!", "--match-set", "TRI-v4-Excluded", "src", "-j", "TRI-Redir-Net"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D OUTPUT -m set ! --match-set TRI-v4-Excluded dst -j TRI-Redir-App --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "OUTPUT", "cr[2:]": ["-m", "set", "!", "--match-set", "TRI-v4-Excluded", "dst", "-j", "TRI-Redir-App"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D OUTPUT -m set ! --match-set TRI-v4-Excluded dst -j TRI-Redir-App --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "OUTPUT", "cr[2:]": ["-m", "set", "!", "--match-set", "TRI-v4-Excluded", "dst", "-j", "TRI-Redir-App"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D OUTPUT -m set ! --match-set TRI-v4-Excluded dst -j TRI-Redir-App --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "OUTPUT", "cr[2:]": ["-m", "set", "!", "--match-set", "TRI-v4-Excluded", "dst", "-j", "TRI-Redir-App"]}
  | ERROR	unable to delete chain	{"table": "nat", "chain": "TRI-Redir-App", "error": "running [/sbin/iptables -t nat -X TRI-Redir-App --wait]: exit status 1: iptables: Too many links.\n"}
  | ERROR	unable to delete chain	{"table": "nat", "chain": "TRI-Redir-Net", "error": "running [/sbin/iptables -t nat -X TRI-Redir-Net --wait]: exit status 1: iptables: Too many links.\n"}
  | ERROR	Failed to clean up ipsets	{"error": "error destroying set exit status 1 (ipset v6.38: Set cannot be destroyed: it is in use by a kernel component\n)"}
  | INFO	Probing cloud providers...
  | INFO	Using generic metadata extractor
  | INFO	Detected machine metadata	{"Attributes": {"ID":"4203431D-D2EF-1BBF-201C-721701C6D2C4","SystemTags":[],"UserTags":[],"FQDN":"ociopf-t-321.dmz","Name":"ociopf-t-321.dmz"}}
  | INFO	Using app credentials
  | INFO	Service	{"api": "https://api.console.aporeto.com "}
  | INFO	Looking for pre existing enforcer	{"namespace": "/bcgov-devex/patch-test", "machine-id": "4203431D-D2EF-1BBF-201C-721701C6D2C4"}
  | INFO	Using enforcer object with parameters	{"id": "5d6955e99b26e2000175ac15", "namespace": "/bcgov-devex/patch-test", "metadata": [], "tags": ["app:k8s:node:annotation:node.openshift.io/md5sum=ffd9fe93f1aa766761e0631c7a945256", "app:k8s:node:annotation:volumes.kubernetes.io/controller-managed-attach-detach=true", "app:k8s:node:architecture=amd64", "app:k8s:node:bootid=e5e0984e-6951-4976-b2ce-8a14c2a33c1f", "app:k8s:node:containerruntimeversion=docker://1.13.1", "app:k8s:node:hostname=ociopf-t-321.dmz", "app:k8s:node:internalip=142.34.217.54", "app:k8s:node:kernelversion=3.10.0-957.27.2.el7.x86_64", "app:k8s:node:kubeletversion=v1.11.0+d4cacc0", "app:k8s:node:kubeproxyversion=v1.11.0+d4cacc0", "app:k8s:node:label:aporeto-agent=true", "app:k8s:node:label:aporeto-enforcerd=true", "app:k8s:node:label:beta.kubernetes.io/arch=amd64", "app:k8s:node:label:beta.kubernetes.io/os=linux", "app:k8s:node:label:kubernetes.io/hostname=ociopf-t-321.dmz", "app:k8s:node:label:logging-infra-fluentd=true", "app:k8s:node:label:node-role.kubernetes.io/compute=true", "app:k8s:node:label:region=app", "app:k8s:node:label:telegraf-agent=true", "app:k8s:node:label:type=compute", "app:k8s:node:label:zone=kamloops", "app:k8s:node:machineid=2564ec4047e646c38a87aed5438a1caf", "app:k8s:node:operatingsystem=linux", "app:k8s:node:osimage=OpenShift", "app:k8s:node:systemuuid=4203431D-D2EF-1BBF-201C-721701C6D2C4", "app:k8s:pod:annotation:kubernetes.io/limit-ranger=LimitRanger plugin set: cpu, memory request for container enforcerd; cpu, memory limit for container enforcerd", "app:k8s:pod:annotation:openshift.io/scc=privileged", "app:k8s:pod:label:app=enforcerd", "app:k8s:pod:label:controller-revision-hash=1959301387", "app:k8s:pod:label:pod-template-generation=2", "app:k8s:pod:label:type=aporeto", "app:k8s:pod:name=enforcerd-7x5xg", "app:k8s:pod:namespace=devops-security-aporeto-enforcers"]}
  | INFO	Validating enforcer identity and uniqueuness ...
  | INFO	Update check enabled	{"currentVersion": "v0.0.0-dev"}
  | ERROR	Unable to initialize ipv6 iptables :%s	{"error": "exec: \"ip6tables\": executable file not found in $PATH"}
  | ERROR	Unable to initialize optional component auditor	{"error": "unable to configure backlog limit in the kernel: operation not permitted"}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D PREROUTING -p tcp -m addrtype --dst-type LOCAL -m set ! --match-set TRI-v4-Excluded src -j TRI-Redir-Net --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "PREROUTING", "cr[2:]": ["-p", "tcp", "-m", "addrtype", "--dst-type", "LOCAL", "-m", "set", "!", "--match-set", "TRI-v4-Excluded", "src", "-j", "TRI-Redir-Net"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D PREROUTING -p tcp -m addrtype --dst-type LOCAL -m set ! --match-set TRI-v4-Excluded src -j TRI-Redir-Net --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "PREROUTING", "cr[2:]": ["-p", "tcp", "-m", "addrtype", "--dst-type", "LOCAL", "-m", "set", "!", "--match-set", "TRI-v4-Excluded", "src", "-j", "TRI-Redir-Net"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D PREROUTING -p tcp -m addrtype --dst-type LOCAL -m set ! --match-set TRI-v4-Excluded src -j TRI-Redir-Net --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "PREROUTING", "cr[2:]": ["-p", "tcp", "-m", "addrtype", "--dst-type", "LOCAL", "-m", "set", "!", "--match-set", "TRI-v4-Excluded", "src", "-j", "TRI-Redir-Net"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D OUTPUT -m set ! --match-set TRI-v4-Excluded dst -j TRI-Redir-App --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "OUTPUT", "cr[2:]": ["-m", "set", "!", "--match-set", "TRI-v4-Excluded", "dst", "-j", "TRI-Redir-App"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D OUTPUT -m set ! --match-set TRI-v4-Excluded dst -j TRI-Redir-App --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "OUTPUT", "cr[2:]": ["-m", "set", "!", "--match-set", "TRI-v4-Excluded", "dst", "-j", "TRI-Redir-App"]}
  | ERROR	Failed to call i.impl.Delete	{"error": "running [/sbin/iptables -t nat -D OUTPUT -m set ! --match-set TRI-v4-Excluded dst -j TRI-Redir-App --wait]: exit status 1: iptables: No chain/target/match by that name.\n", "cr[0]": "nat", "cr[1]": "OUTPUT", "cr[2:]": ["-m", "set", "!", "--match-set", "TRI-v4-Excluded", "dst", "-j", "TRI-Redir-App"]}
  | ERROR	unable to delete chain	{"table": "nat", "chain": "TRI-Redir-App", "error": "running [/sbin/iptables -t nat -X TRI-Redir-App --wait]: exit status 1: iptables: Too many links.\n"}
  | ERROR	unable to delete chain	{"table": "nat", "chain": "TRI-Redir-Net", "error": "running [/sbin/iptables -t nat -X TRI-Redir-Net --wait]: exit status 1: iptables: Too many links.\n"}
  | ERROR	Error when starting the supervisor	{"error": "unable to start the implementer: Unable to initialize chains: running [/sbin/iptables -t nat -N TRI-Redir-App --wait]: exit status 1: iptables: Chain already exists.\n"}
  | FATAL	Unable to start controllers	{"error": "Failed to activate controler: Error while starting supervisor unable to start the implementer: Unable to initialize chains: running [/sbin/iptables -t nat -N TRI-Redir-App --wait]: exit status 1: iptables: Chain already exists.\n"}


```

**Comment by stewartshea** [comment]
@wmhutchison are you able to perform these steps again on node 321?

https://github.com/BCDevOps/platform-services/issues/167#issuecomment-525830263

Thanks!

**Comment by stewartshea** [comment]
@mheese @amitlimaye has this one been resolved in the latest 3.11.10 release or is it an ongoing issue?

**Comment by wmhutchison** [comment]
> @wmhutchison are you able to perform these steps again on node 321?
> 
> [#167 (comment)](https://github.com/BCDevOps/platform-services/issues/167#issuecomment-525830263)
> 
> Thanks!

@stewartshea Done.

**Comment by stewartshea** [comment]
> > @wmhutchison are you able to perform these steps again on node 321?
> > [#167 (comment)](https://github.com/BCDevOps/platform-services/issues/167#issuecomment-525830263)
> > Thanks!
> 
> @stewartshea Done.

@wmhutchison thanks!

**Comment by mheese** [comment]
ah ... yeah, I posted this into the rocket chat:

```
...
 here is what happened:
1. you had a 3.9 enforcer installed
2. you deleted/killed that enforcer
3. during the shutdown period, there was not enough time for the enforcer to run the cleanup
4. a new 3.11 enforcer started
5. the same cleanup is also run on startup ... however, the chain names have slightly changed between 3.9 and 3.11, so that cleanup didn't work
6. the adding of new chains failed because of the missed cleanup

my colleague has added additional logic now to catch this ... however, I believe this is not in the 3.11.10 release yet ... in the meantime, it is easy to resolve: ensure an old 3.9 enforcer has time enough for cleanup when it shuts down

```

you might be able to help yourself by using the suggested `terminationGracePeriodSeconds: 60` for the daemonset that is running the 3.9 enforcers

**Comment by stewartshea** [comment]
Thanks @mheese. My install process takes care of completely removing all components of the deployment and then re-installing them, rather than just changing the image tag, so the daemonset update has been appropriately applied.

**Comment by stewartshea** [comment]
I'm still seeing an issue with the same node @mheese, but the error is now different: 

```

{"l":"error","t":1567548483.5996163,"c":"nflog/nflog_linux.go:77","m":"destNFLogsHandler: create flow record","error":"nflog: prefix doesn't contain sufficient information: 3c83a0a6069e:default:default6"}
--
  | {"l":"error","t":1567548483.5996392,"c":"nflog/nflog_linux.go:77","m":"destNFLogsHandler: create flow record","error":"nflog: prefix doesn't contain sufficient information: 3c83a0a6069e:default:default6"}
  | {"l":"error","t":1567548483.5996604,"c":"nflog/nflog_linux.go:77","m":"destNFLogsHandler: create flow record","error":"nflog: prefix doesn't contain sufficient information: 3c83a0a6069e:default:default6"}
  | {"l":"error","t":1567548483.5996814,"c":"nflog/nflog_linux.go:77","m":"destNFLogsHandler: create flow record","error":"nflog: prefix doesn't contain sufficient information: 3c83a0a6069e:default:default6"}
  | {"l":"error","t":1567548483.5997074,"c":"nflog/nflog_linux.go:77","m":"destNFLogsHandler: create flow record","error":"nflog: prefix doesn't contain sufficient information: 3c83a0a6069e:default:default6"}
  | {"l":"error","t":1567548483.6234667,"c":"profile/retrieve.go:158","m":"Failed to retrieve enforcer profile","enforcerID":"5d6ea7af9b26e2000176d3f5","error":"Cannot communicate: Get https://api.console.aporeto.com/v/1/enforcers/5d6ea7af9b26e2000176d3f5/enforcerprofiles:  dial tcp: lookup api.console.aporeto.com on 142.34.217.54:53: write udp 142.34.217.54:54618->142.34.217.54:53: write: operation not permitted"}
  | {"l":"error","t":1567548483.6235602,"c":"policy/syncjobs.go:153","m":"Unable update profile with interface info","error":"unable to retrieve enforcer profile: Cannot communicate: Get https://api.console.aporeto.com/v/1/enforcers/5d6ea7af9b26e2000176d3f5/enforcerprofiles:  dial tcp: lookup api.console.aporeto.com on 142.34.217.54:53: write udp 142.34.217.54:54618->142.34.217.54:53: write: operation not permitted"}


... 

{"l":"error","t":1567548546.8213933,"m":"unable to delete chain","srv":"d17fc7d7-ca88-11e9-9387-00505683394a","table":"nat","chain":"TRI-Redir-Net","error":"running [/sbin/iptables -t nat -X TRI-Redir-Net --wait]: exit status 1: iptables: Too many links.\n"}
--
  | {"l":"info","t":1567548546.9229312,"m":"Remote enforcer exiting ...","srv":"d17fc7d7-ca88-11e9-9387-00505683394a"}
  | {"l":"error","t":1567548547.1186144,"c":"policy/syncjobs.go:385","m":"Failed on attempt to recreate failed pu","error":"unable to setup enforcer: unable to start the implementer: Unable to initialize chains: running [/sbin/iptables -t nat -N TRI-Redir-App --wait]: exit status 1: iptables: Chain already exists.\n","state":4}
  | {"l":"error","t":1567548547.5194592,"m":"unable to delete chain","srv":"d2d47d87-ca88-11e9-9387-00505683394a","table":"nat","chain":"TRI-Redir-App","error":"running [/sbin/iptables -t nat -X TRI-Redir-App --wait]: exit status 1: iptables: Too many links.\n"}


```

**Comment by amitlimaye** [comment]
We are testing a fix for this which will eliminate the need to run these commands manually. This error you are seeing is because there is still a rule pointing to these chains. 
We will clean these things up as a part of enforcer startup. I am testing this code and you should have a release in a day or two which should fix this

**Comment by stewartshea** [comment]
Thanks @amitlimaye

**Comment by stewartshea** [comment]
waiting on this one additional fix. I don't think it was added to 3.11.11.

**Comment by mheese** [comment]
@stewartshea correct, we did a release early in the morning today, unfortunately we were lacking somebody from management today who could have approved and authorized to make that release public.

I will let you know as soon as I have an update

**Comment by stewartshea** [comment]
Still having an issue on ociopf-t-321.dmz - the agent wouldn't terminate properly. Terminated it manually and it's back in a crash loop. This is expected as we are still waiting for the new version.

```

               __                            _
    ___ _ __  / _| ___  _ __ ___ ___ _ __ __| |
   / _ \ '_ \| |_ / _ \| '__/ __/ _ \ '__/ _' |
  |  __/ | | |  _| (_) | | | (_|  __/ | | (_| |
   \___|_| |_|_|  \___/|_|  \___\___|_|  \__,_|

   Aporeto Enforcer Agent
   v1.901.17 - 31cb02ba949adf6b354bb4d677f2750209f84e8e
 _______________________________________________________________

{"l":"info","t":1568005566.4853084,"m":"Probing cloud providers..."}
{"l":"info","t":1568005567.9856646,"m":"Using generic metadata extractor"}
{"l":"info","t":1568005568.0228844,"m":"Detected machine metadata","Attributes":{"ID":"4203431D-D2EF-1BBF-201C-721701C6D2C4","SystemTags":[],"UserTags":[],"FQDN":"ociopf-t-321.dmz","Name":"ociopf-t-321.dmz"}}
{"l":"info","t":1568005568.0444794,"m":"Using app credentials"}
{"l":"info","t":1568005568.0445232,"m":"Service","api":"https://api.console.aporeto.com "}
{"l":"info","t":1568005568.3900979,"m":"Looking for pre existing enforcer","namespace":"/bcgov/test/lab-pathfinder","machine-id":"4203431D-D2EF-1BBF-201C-721701C6D2C4"}
{"l":"info","t":1568005568.7071242,"m":"Using enforcer object with parameters","id":"5d75dd2d9b26e2000177dfb3","namespace":"/bcgov/test/lab-pathfinder","metadata":[],"tags":["app:k8s:node:annotation:node.openshift.io/md5sum=ffd9fe93f1aa766761e0631c7a945256","app:k8s:node:annotation:volumes.kubernetes.io/controller-managed-attach-detach=true","app:k8s:node:architecture=amd64","app:k8s:node:bootid=c2732476-0aa3-48df-8287-6879503a7a5d","app:k8s:node:containerruntimeversion=docker://1.13.1","app:k8s:node:hostname=ociopf-t-321.dmz","app:k8s:node:internalip=142.34.217.54","app:k8s:node:kernelversion=3.10.0-957.27.2.el7.x86_64","app:k8s:node:kubeletversion=v1.11.0+d4cacc0","app:k8s:node:kubeproxyversion=v1.11.0+d4cacc0","app:k8s:node:label:aporeto-agent=true","app:k8s:node:label:aporeto-enforcerd=true","app:k8s:node:label:beta.kubernetes.io/arch=amd64","app:k8s:node:label:beta.kubernetes.io/os=linux","app:k8s:node:label:kubernetes.io/hostname=ociopf-t-321.dmz","app:k8s:node:label:logging-infra-fluentd=true","app:k8s:node:label:node-role.kubernetes.io/compute=true","app:k8s:node:label:region=app","app:k8s:node:label:telegraf-agent=true","app:k8s:node:label:type=compute","app:k8s:node:label:zone=kamloops","app:k8s:node:machineid=2564ec4047e646c38a87aed5438a1caf","app:k8s:node:operatingsystem=linux","app:k8s:node:osimage=OpenShift","app:k8s:node:systemuuid=4203431D-D2EF-1BBF-201C-721701C6D2C4","app:k8s:pod:annotation:kubernetes.io/limit-ranger=LimitRanger plugin set: cpu, memory request for container enforcerd; cpu, memory limit for container enforcerd","app:k8s:pod:annotation:openshift.io/scc=privileged","app:k8s:pod:label:app=enforcerd","app:k8s:pod:label:controller-revision-hash=555153027","app:k8s:pod:label:pod-template-generation=2","app:k8s:pod:label:type=aporeto","app:k8s:pod:name=enforcerd-ffnhs","app:k8s:pod:namespace=devops-security-aporeto-enforcers"]}
{"l":"info","t":1568005573.8235273,"m":"Validating enforcer identity and uniqueuness ..."}
{"l":"info","t":1568005644.4715214,"m":"Update check enabled","currentVersion":"v1.901.17"}
{"l":"info","t":1568005644.473662,"m":"Enabling Trireme Datapath v1.0"}
{"l":"error","t":1568005644.553191,"m":"Unable to initialize optional component auditor","error":"unable to configure backlog limit in the kernel: operation not permitted"}
{"l":"fatal","t":1568005660.664638,"m":"Unable to initialize netfilter queue","QueueNum":16,"error":"Error binding to queue: Netlink Returned errror -1 "}
```

**Comment by stewartshea** [comment]
@mheese @amitlimaye any updates on this issue? Thanks

**Comment by stewartshea** [comment]
Upgraded to 3.11.13; 

```

__                            _
--
  | ___ _ __  / _\| ___  _ __ ___ ___ _ __ __\| \|
  | / _ \ '_ \\| \|_ / _ \\| '__/ __/ _ \ '__/ _' \|
  | \|  __/ \| \| \|  _\| (_) \| \| \| (_\|  __/ \| \| (_\| \|
  | \___\|_\| \|_\|_\|  \___/\|_\|  \___\___\|_\|  \__,_\|
  |  
  | Aporeto Enforcer Agent
  | v1.901.20 - a5aa2b6c194e5e59458b1a001909cbc4efb8f589
  | _______________________________________________________________
  |  
  | {"l":"info","t":1568649481.6668859,"m":"Probing cloud providers..."}
  | {"l":"info","t":1568649483.167214,"m":"Using generic metadata extractor"}
  | {"l":"info","t":1568649483.2037582,"m":"Detected machine metadata","Attributes":{"ID":"4203431D-D2EF-1BBF-201C-721701C6D2C4","SystemTags":[],"UserTags":[],"FQDN":"ociopf-t-321.dmz","Name":"ociopf-t-321.dmz"}}
  | {"l":"info","t":1568649483.25194,"m":"Using app credentials"}
  | {"l":"info","t":1568649483.2520025,"m":"Service","api":"https://api.console.aporeto.com "}
  | {"l":"info","t":1568649483.6412022,"m":"Looking for pre existing enforcer","namespace":"/bcgov/test/lab-pathfinder","machine-id":"4203431D-D2EF-1BBF-201C-721701C6D2C4"}
  | {"l":"fatal","t":1568649483.9548478,"m":"Unable to register enforcer","error":"multiple enforcers matching configuration: please delete"}

```

Removed the previous entry and ended up with the following: 

```

__                            _
--
  | ___ _ __  / _\| ___  _ __ ___ ___ _ __ __\| \|
  | / _ \ '_ \\| \|_ / _ \\| '__/ __/ _ \ '__/ _' \|
  | \|  __/ \| \| \|  _\| (_) \| \| \| (_\|  __/ \| \| (_\| \|
  | \___\|_\| \|_\|_\|  \___/\|_\|  \___\___\|_\|  \__,_\|
  |  
  | Aporeto Enforcer Agent
  | v1.901.20 - a5aa2b6c194e5e59458b1a001909cbc4efb8f589
  | _______________________________________________________________
  |  
  | {"l":"info","t":1568649791.3513732,"m":"Probing cloud providers..."}
  | {"l":"info","t":1568649792.851694,"m":"Using generic metadata extractor"}
  | {"l":"info","t":1568649792.9039936,"m":"Detected machine metadata","Attributes":{"ID":"4203431D-D2EF-1BBF-201C-721701C6D2C4","SystemTags":[],"UserTags":[],"FQDN":"ociopf-t-321.dmz","Name":"ociopf-t-321.dmz"}}
  | {"l":"info","t":1568649792.9519315,"m":"Using app credentials"}
  | {"l":"info","t":1568649792.9519908,"m":"Service","api":"https://api.console.aporeto.com "}
  | {"l":"info","t":1568649793.2819502,"m":"Looking for pre existing enforcer","namespace":"/bcgov/test/lab-pathfinder","machine-id":"4203431D-D2EF-1BBF-201C-721701C6D2C4"}
  | {"l":"info","t":1568649793.581996,"m":"Using enforcer object with parameters","id":"5d7fb221311ddc000146e931","namespace":"/bcgov/test/lab-pathfinder","metadata":[],"tags":["app:k8s:node:annotation:node.openshift.io/md5sum=ffd9fe93f1aa766761e0631c7a945256","app:k8s:node:annotation:volumes.kubernetes.io/controller-managed-attach-detach=true","app:k8s:node:architecture=amd64","app:k8s:node:bootid=c2732476-0aa3-48df-8287-6879503a7a5d","app:k8s:node:containerruntimeversion=docker://1.13.1","app:k8s:node:hostname=ociopf-t-321.dmz","app:k8s:node:internalip=142.34.217.54","app:k8s:node:kernelversion=3.10.0-957.27.2.el7.x86_64","app:k8s:node:kubeletversion=v1.11.0+d4cacc0","app:k8s:node:kubeproxyversion=v1.11.0+d4cacc0","app:k8s:node:label:aporeto-agent=true","app:k8s:node:label:aporeto-enforcerd=true","app:k8s:node:label:beta.kubernetes.io/arch=amd64","app:k8s:node:label:beta.kubernetes.io/os=linux","app:k8s:node:label:kubernetes.io/hostname=ociopf-t-321.dmz","app:k8s:node:label:logging-infra-fluentd=true","app:k8s:node:label:node-role.kubernetes.io/compute=true","app:k8s:node:label:region=app","app:k8s:node:label:telegraf-agent=true","app:k8s:node:label:type=compute","app:k8s:node:label:zone=kamloops","app:k8s:node:machineid=2564ec4047e646c38a87aed5438a1caf","app:k8s:node:operatingsystem=linux","app:k8s:node:osimage=OpenShift","app:k8s:node:systemuuid=4203431D-D2EF-1BBF-201C-721701C6D2C4","app:k8s:pod:annotation:kubernetes.io/limit-ranger=LimitRanger plugin set: cpu, memory request for container enforcerd; cpu, memory limit for container enforcerd","app:k8s:pod:annotation:openshift.io/scc=privileged","app:k8s:pod:label:app=enforcerd","app:k8s:pod:label:controller-revision-hash=3775912365","app:k8s:pod:label:pod-template-generation=3","app:k8s:pod:label:type=aporeto","app:k8s:pod:name=enforcerd-7dhw6","app:k8s:pod:namespace=devops-security-aporeto-enforcers"]}
  | {"l":"info","t":1568649799.1094775,"m":"Validating enforcer identity and uniqueuness ..."}
  | {"l":"info","t":1568649870.1757963,"m":"Update check enabled","currentVersion":"v1.901.20"}
  | {"l":"info","t":1568649870.1775928,"m":"Enabling Trireme Datapath v1.0"}
  | {"l":"error","t":1568649870.255167,"m":"Unable to initialize optional component auditor","error":"unable to configure backlog limit in the kernel: operation not permitted"}
  | {"l":"fatal","t":1568649886.5541112,"m":"Unable to initialize netfilter queue","QueueNum":16,"error":"Error binding to queue: Netlink Returned errror -1 "}



```

**Comment by dstiliadis** [comment]
It seems that there are two enforcers running at the same time. Even though the previous daemonset is destroyed, it takes some time for all enforcers to terminate. Then the new daemonset comes up and they start fighting each other. Can you make sure that all enforcer pods are destroyed before firing up the new daemonset?

**Comment by stewartshea** [comment]
@dstiliadis I believe you are looking at the output of the first one and not the second one, but I'll completely remove it all and redeploy and post the results shortly

**Comment by stewartshea** [comment]
@dstiliadis Completely removed and redeployed; here is the log from the enforcer on the failing node; 

```

___ _ __  / _\| ___  _ __ ___ ___ _ __ __\| \|
--
  | / _ \ '_ \\| \|_ / _ \\| '__/ __/ _ \ '__/ _' \|
  | \|  __/ \| \| \|  _\| (_) \| \| \| (_\|  __/ \| \| (_\| \|
  | \___\|_\| \|_\|_\|  \___/\|_\|  \___\___\|_\|  \__,_\|
  |  
  | Aporeto Enforcer Agent
  | v1.901.20 - a5aa2b6c194e5e59458b1a001909cbc4efb8f589
  | _______________________________________________________________
  |  
  | {"l":"info","t":1568657096.6770933,"m":"Probing cloud providers..."}
  | {"l":"info","t":1568657098.1774333,"m":"Using generic metadata extractor"}
  | {"l":"info","t":1568657098.212406,"m":"Detected machine metadata","Attributes":{"ID":"4203431D-D2EF-1BBF-201C-721701C6D2C4","SystemTags":[],"UserTags":[],"FQDN":"ociopf-t-321.dmz","Name":"ociopf-t-321.dmz"}}
  | {"l":"info","t":1568657098.2503948,"m":"Using app credentials"}
  | {"l":"info","t":1568657098.250467,"m":"Service","api":"https://api.console.aporeto.com "}
  | {"l":"info","t":1568657098.6058345,"m":"Looking for pre existing enforcer","namespace":"/bcgov/test/lab-pathfinder","machine-id":"4203431D-D2EF-1BBF-201C-721701C6D2C4"}
  | {"l":"info","t":1568657098.9335501,"m":"Using enforcer object with parameters","id":"5d7fceaa311ddc000146ec04","namespace":"/bcgov/test/lab-pathfinder","metadata":[],"tags":["app:k8s:node:annotation:node.openshift.io/md5sum=ffd9fe93f1aa766761e0631c7a945256","app:k8s:node:annotation:volumes.kubernetes.io/controller-managed-attach-detach=true","app:k8s:node:architecture=amd64","app:k8s:node:bootid=c2732476-0aa3-48df-8287-6879503a7a5d","app:k8s:node:containerruntimeversion=docker://1.13.1","app:k8s:node:hostname=ociopf-t-321.dmz","app:k8s:node:internalip=142.34.217.54","app:k8s:node:kernelversion=3.10.0-957.27.2.el7.x86_64","app:k8s:node:kubeletversion=v1.11.0+d4cacc0","app:k8s:node:kubeproxyversion=v1.11.0+d4cacc0","app:k8s:node:label:aporeto-agent=true","app:k8s:node:label:aporeto-enforcerd=true","app:k8s:node:label:beta.kubernetes.io/arch=amd64","app:k8s:node:label:beta.kubernetes.io/os=linux","app:k8s:node:label:kubernetes.io/hostname=ociopf-t-321.dmz","app:k8s:node:label:logging-infra-fluentd=true","app:k8s:node:label:node-role.kubernetes.io/compute=true","app:k8s:node:label:region=app","app:k8s:node:label:telegraf-agent=true","app:k8s:node:label:type=compute","app:k8s:node:label:zone=kamloops","app:k8s:node:machineid=2564ec4047e646c38a87aed5438a1caf","app:k8s:node:operatingsystem=linux","app:k8s:node:osimage=OpenShift","app:k8s:node:systemuuid=4203431D-D2EF-1BBF-201C-721701C6D2C4","app:k8s:pod:annotation:kubernetes.io/limit-ranger=LimitRanger plugin set: cpu, memory request for container enforcerd; cpu, memory limit for container enforcerd","app:k8s:pod:annotation:openshift.io/scc=privileged","app:k8s:pod:label:app=enforcerd","app:k8s:pod:label:controller-revision-hash=3775912365","app:k8s:pod:label:pod-template-generation=2","app:k8s:pod:label:type=aporeto","app:k8s:pod:name=enforcerd-9n2pr","app:k8s:pod:namespace=devops-security-aporeto-enforcers"]}
  | {"l":"info","t":1568657104.8444257,"m":"Validating enforcer identity and uniqueuness ..."}
  | {"l":"info","t":1568657172.504995,"m":"Update check enabled","currentVersion":"v1.901.20"}
  | {"l":"info","t":1568657172.506362,"m":"Enabling Trireme Datapath v1.0"}
  | {"l":"error","t":1568657172.6036048,"m":"Unable to initialize optional component auditor","error":"unable to configure backlog limit in the kernel: operation not permitted"}
  | {"l":"fatal","t":1568657188.776917,"m":"Unable to initialize netfilter queue","QueueNum":16,"error":"Error binding to queue: Netlink Returned errror -1 "}


```

**Comment by brianonn** [comment]
@stewartshea I sent a slack message to you too

**Comment by stewartshea** [comment]
Kernel seemed in a bad state, also saw this on the node: 

```
[root@ociopf-t-321 ~]# w
 12:32:41 up 9 days, 23:09,  1 user,  load average: 153.47, 154.99, 156.56
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
root     pts/0    HP-              12:31    1.00s  0.25s  0.10s w
[root@ociopf-t-321 ~]# ps aux | grep Z
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        489  0.0  0.0      0     0 ?        Zl   Sep06   0:16 [remoteenforcerd] <defunct>
root       3062  0.0  0.0      0     0 ?        Zl   Sep06   0:57 [remoteenforcerd] <defunct>
root       6116  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
root      10129  0.0  0.0      0     0 ?        Zl   Sep06   0:29 [remoteenforcerd] <defunct>
root      12304  0.0  0.0      0     0 ?        Zl   Sep06   0:53 [remoteenforcerd] <defunct>
root      13092  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
root      21457  0.0  0.0      0     0 ?        Zl   Sep06   0:11 [remoteenforcerd] <defunct>
root      21506  0.0  0.0      0     0 ?        Zl   Sep06   0:25 [remoteenforcerd] <defunct>
root      22412  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
root      22961  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
root      23937  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
root      24843  0.0  0.0      0     0 ?        Z    Sep07   0:00 [iptables] <defunct>
root      32537  0.0  0.0      0     0 ?        Zl   Sep06   0:50 [remoteenforcerd] <defunct>
root      42219  0.0  0.0      0     0 ?        Zl   Sep06   0:39 [remoteenforcerd] <defunct>
root      42877  0.0  0.0      0     0 ?        Zl   Sep07   0:09 [remoteenforcerd] <defunct>
root      46798  0.0  0.0      0     0 ?        Z    Sep06   0:51 [remoteenforcerd] <defunct>
root      48206  0.0  0.0   9092   928 pts/0    S+   12:32   0:00 grep --color=auto Z
root      48427  0.0  0.0      0     0 ?        Zl   Sep06   0:54 [remoteenforcerd] <defunct>
root      49641  0.0  0.0      0     0 ?        Zl   Sep07   0:01 [remoteenforcerd] <defunct>
root      53746  0.0  0.0      0     0 ?        Zl   Sep07   0:07 [remoteenforcerd] <defunct>
root      54703  0.0  0.0      0     0 ?        Zl   Sep06   0:45 [remoteenforcerd] <defunct>
root      59975  0.0  0.0      0     0 ?        Z    Sep07   0:01 [remoteenforcerd] <defunct>
root      60361  0.0  0.0      0     0 ?        Zl   Sep07   0:02 [remoteenforcerd] <defunct>
root      65344  0.0  0.0      0     0 ?        Zl   Sep07   0:09 [remoteenforcerd] <defunct>
root      73013  0.0  0.0      0     0 ?        Zl   Sep06   0:15 [remoteenforcerd] <defunct>
root      77378  0.0  0.0      0     0 ?        Zl   Sep06   0:41 [remoteenforcerd] <defunct>
root      82590  0.0  0.0      0     0 ?        Z    Sep06   0:47 [remoteenforcerd] <defunct>
root      88543  0.0  0.0      0     0 ?        Zl   Sep07   0:01 [remoteenforcerd] <defunct>
root      98820  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
root     102249  0.0  0.0      0     0 ?        Zl   Sep07   0:02 [remoteenforcerd] <defunct>
root     102591  0.0  0.0      0     0 ?        Zl   Sep06   0:44 [remoteenforcerd] <defunct>
root     102643  0.0  0.0      0     0 ?        Zl   Sep06   0:20 [remoteenforcerd] <defunct>
root     104613  0.0  0.0      0     0 ?        Zl   Sep07   0:02 [remoteenforcerd] <defunct>
root     104876  0.0  0.0      0     0 ?        Z    Sep06   0:12 [remoteenforcerd] <defunct>
root     105068  0.0  0.0      0     0 ?        Zl   Sep06   0:52 [remoteenforcerd] <defunct>
root     108178  0.0  0.0      0     0 ?        Zl   Sep06   0:12 [remoteenforcerd] <defunct>
root     108332  0.0  0.0      0     0 ?        Z    Sep06   0:17 [remoteenforcerd] <defunct>
root     109478  0.0  0.0      0     0 ?        Z    Sep07   0:01 [remoteenforcerd] <defunct>
root     109791  0.0  0.0      0     0 ?        Zl   Sep07   0:12 [remoteenforcerd] <defunct>
root     114777  0.0  0.0      0     0 ?        Zl   Sep06   0:45 [remoteenforcerd] <defunct>
root     119303  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
root     119920  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
root     124273  0.0  0.0      0     0 ?        Zl   Sep07   0:02 [remoteenforcerd] <defunct>
root     124420  0.0  0.0      0     0 ?        Zl   Sep07   0:00 [remoteenforcerd] <defunct>
```

Appears that a reboot has cleared the issue .

**Comment by stewartshea** [comment]
last entry was this for OOM:

Sep 16 12:50:53 ociopf-t-321.dmz kernel: Memory cgroup out of memory: Kill process 111476 (enforcerd) score 1118 or sacrifice child
Sep 16 12:50:53 ociopf-t-321.dmz kernel: Killed process 33879 (remoteenforcerd) total-vm:141852kB, anon-rss:26152kB, file-rss:8kB, shmem-rss:10
more recent message:

Sep 16 12:55:22 ociopf-t-321.dmz kernel: INFO: task remoteenforcerd:113437 blocked for more than 120 seconds.
Sep 16 12:55:22 ociopf-t-321.dmz kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 16 12:55:22 ociopf-t-321.dmz kernel: remoteenforcerd D ffff954c51b40000     0 113437  83560 0x00000080
Sep 16 12:55:22 ociopf-t-321.dmz kernel: Call Trace:
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff814e2598>] ? check_preempt_wakeup+0x148/0x250
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff81b69f19>] schedule+0x29/0x70
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff81b67a21>] schedule_timeout+0x221/0x2d0
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff81434919>] ? sched_clock+0x9/0x10
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff814db1f5>] ? sched_clock_cpu+0x85/0xc0
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff814d7980>] ? try_to_wake_up+0x190/0x390
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff81b6a2cd>] wait_for_completion+0xfd/0x140
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff814d7c40>] ? wake_up_state+0x20/0x20
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff816ac685>] do_coredump+0x3a5/0xac0
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff814d7980>] ? try_to_wake_up+0x190/0x390
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff81b717c8>] ? __do_page_fault+0x3c8/0x4f0
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff814d7c30>] ? wake_up_state+0x10/0x20
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff814ad0e3>] ? __sigqueue_free.part.13+0x33/0x40
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff814b0495>] get_signal_to_deliver+0x1c5/0x5e0
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff8142b527>] do_signal+0x57/0x6f0
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff8142bc32>] do_notify_resume+0x72/0xc0
Sep 16 12:55:22 ociopf-t-321.dmz kernel:  [<ffffffff81b77134>] int_signal+0x12/0x17
the latter is recurring:

Sep 16 12:57:22 ociopf-t-321.dmz kernel: INFO: task remoteenforcerd:113437 blocked for more than 120 seconds.
Sep 16 12:57:22 ociopf-t-321.dmz kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 16 12:57:22 ociopf-t-321.dmz kernel: remoteenforcerd D ffff954c51b40000     0 113437  83560 0x00000080
Sep 16 12:57:22 ociopf-t-321.dmz kernel: Call Trace:
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff814e2598>] ? check_preempt_wakeup+0x148/0x250
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff81b69f19>] schedule+0x29/0x70
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff81b67a21>] schedule_timeout+0x221/0x2d0
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff81434919>] ? sched_clock+0x9/0x10
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff814db1f5>] ? sched_clock_cpu+0x85/0xc0
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff814d7980>] ? try_to_wake_up+0x190/0x390
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff81b6a2cd>] wait_for_completion+0xfd/0x140
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff814d7c40>] ? wake_up_state+0x20/0x20
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff816ac685>] do_coredump+0x3a5/0xac0
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff814d7980>] ? try_to_wake_up+0x190/0x390
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff81b717c8>] ? __do_page_fault+0x3c8/0x4f0
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff814d7c30>] ? wake_up_state+0x10/0x20
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff814ad0e3>] ? __sigqueue_free.part.13+0x33/0x40
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff814b0495>] get_signal_to_deliver+0x1c5/0x5e0
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff8142b527>] do_signal+0x57/0x6f0
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff8142bc32>] do_notify_resume+0x72/0xc0
Sep 16 12:57:22 ociopf-t-321.dmz kernel:  [<ffffffff81b77134>] int_signal+0x12/0x17

**Comment by stewartshea** [comment]
@brianonn See above, any thoughts?

**Comment by brianonn** [comment]
looking into that now @stewartshea

**Comment by brianonn** [comment]
@stewartshea  so why did enforcerd get OOM killed?  how much memory is on that node ?

**Comment by stewartshea** [comment]
@wmhutchison can I get you to tag in here? I have no visibility at the node level

**Comment by stewartshea** [comment]
regarding the dns resolution, I've fixed that now. It was a result of us changing to a more native zero-trust model and not having the right policy in place. Its interesting though since I thought the enforcer namespace was excluded from any network policy, hence resolution theoretically should have worked.

**Comment by wmhutchison** [comment]
First instance in logs post-reboot showing an oom condition:

```
Sep 16 12:39:04 ociopf-t-321.dmz kernel: iptables-restor invoked oom-killer: gfp_mask=0x50, order=0, oom_score_adj=993
Sep 16 12:39:04 ociopf-t-321.dmz kernel: iptables-restor cpuset=docker-b45da1feed6df60107b15e61dacf3c661be48c9105d74133c7b54124c1087836.scope mems_allowed=0
Sep 16 12:39:04 ociopf-t-321.dmz kernel: CPU: 7 PID: 51295 Comm: iptables-restor Not tainted 3.10.0-957.27.2.el7.x86_64 #1
Sep 16 12:39:04 ociopf-t-321.dmz kernel: Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 09/19/2018
Sep 16 12:39:04 ociopf-t-321.dmz kernel: Call Trace:
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81b64147>] dump_stack+0x19/0x1b
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81b5eb6a>] dump_header+0x90/0x229
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff8170207b>] ? cred_has_capability+0x6b/0x120
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81522e44>] ? __css_tryget+0x24/0x50
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81632a38>] ? try_get_mem_cgroup_from_mm+0x28/0x60
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff815bb904>] oom_kill_process+0x254/0x3d0
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81636c36>] mem_cgroup_oom_synchronize+0x546/0x570
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff816360b0>] ? mem_cgroup_charge_common+0xc0/0xc0
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff815bc194>] pagefault_out_of_memory+0x14/0x90
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81b5d072>] mm_fault_error+0x6a/0x157
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81b717c8>] __do_page_fault+0x3c8/0x4f0
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81b71925>] do_page_fault+0x35/0x90
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81b6dab6>] ? error_swapgs+0xa7/0xbd
Sep 16 12:39:04 ociopf-t-321.dmz kernel:  [<ffffffff81b6d768>] page_fault+0x28/0x30
Sep 16 12:39:04 ociopf-t-321.dmz kernel: Task in /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod65fd6436_d8ac_11e9_9671_00505683c9cc.slice/docker-b45da1feed6df60107b15e61dacf3c661be48c9105d74133c7b54124c1087836.scope killed as a result of limit of /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod65fd6436_d8ac_11e9_9671_00505683c9cc.slice
Sep 16 12:39:04 ociopf-t-321.dmz kernel: memory: usage 1048576kB, limit 1048576kB, failcnt 125846
Sep 16 12:39:04 ociopf-t-321.dmz kernel: memory+swap: usage 1048576kB, limit 9007199254740988kB, failcnt 0
Sep 16 12:39:04 ociopf-t-321.dmz kernel: kmem: usage 0kB, limit 9007199254740988kB, failcnt 0
Sep 16 12:39:04 ociopf-t-321.dmz kernel: Memory cgroup stats for /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod65fd6436_d8ac_11e9_9671_00505683c9cc.slice: cache:0KB rss:0KB rss_huge:0KB mapped_file:0KB swap:0KB inactive_anon:0KB active_anon:0KB inactive_file:0KB active_file:0KB unevictable:0KB
Sep 16 12:39:04 ociopf-t-321.dmz kernel: Memory cgroup stats for /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod65fd6436_d8ac_11e9_9671_00505683c9cc.slice/docker-79ab322724d7214773d0b6fd74683126361241cc925cc03eaf9483abab7c4f3c.scope: cache:0KB rss:424KB rss_huge:0KB mapped_file:0KB swap:0KB inactive_anon:0KB active_anon:424KB inactive_file:0KB active_file:0KB unevictable:0KB
Sep 16 12:39:04 ociopf-t-321.dmz kernel: Memory cgroup stats for /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod65fd6436_d8ac_11e9_9671_00505683c9cc.slice/docker-b45da1feed6df60107b15e61dacf3c661be48c9105d74133c7b54124c1087836.scope: cache:41176KB rss:1006976KB rss_huge:811008KB mapped_file:12272KB swap:0KB inactive_anon:29136KB active_anon:1017824KB inactive_file:668KB active_file:484KB unevictable:0KB
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [ 7451]  1001  7451      685       83       6        0          -998 pod
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [ 8427]     0  8427    71103    33320     112        0           993 enforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [32466]     0 32466    35317     8783      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [33054]     0 33054    35381     9313      37        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [33459]     0 33459    35532     8670      37        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [33939]     0 33939    35404     8985      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [34290]     0 34290    35381     8795      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [34684]     0 34684    35340     8794      37        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [34697]     0 34697    35317     8787      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [35681]     0 35681    35468     8845      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [36358]     0 36358    35404     8864      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [37196]     0 37196    35271     8864      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [37607]     0 37607    35555     9283      37        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [37724]     0 37724    35381     8916      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [38062]     0 38062    35445     8858      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [38874]     0 38874    35381     8855      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [39022]     0 39022    35514     8980      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [39153]     0 39153    35358     8860      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [40909]     0 40909    35381     9365      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [41345]     0 41345    35317     8858      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [41754]     0 41754    35445     8861      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [42973]     0 42973    35381     9181      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [43111]     0 43111    35404     8854      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [43198]     0 43198    35404     8801      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [43499]     0 43499    35422     8793      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [44687]     0 44687    35578     8977      37        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [44845]     0 44845    35404     8285      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [44864]     0 44864    35317     8852      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [45146]     0 45146    35358     8412      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [46488]     0 46488    35404     8167      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [46671]     0 46671    35358     7389      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [46686]     0 46686    35271     6205      34        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [47205]     0 47205    35381     7778      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [48622]     0 48622    35358     4722      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [49215]     0 49215    35532     7196      35        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [49223]     0 49223    35381     7535      36        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [49702]     0 49702    35317     6969      34        0           993 remoteenforcerd
Sep 16 12:39:04 ociopf-t-321.dmz kernel: [51295]     0 51295     7546       50      21        0           993 iptables-restor
Sep 16 12:39:04 ociopf-t-321.dmz kernel: Memory cgroup out of memory: Kill process 50558 (enforcerd) score 1116 or sacrifice child
Sep 16 12:39:04 ociopf-t-321.dmz kernel: Killed process 40909 (remoteenforcerd) total-vm:141524kB, anon-rss:27324kB, file-rss:4kB, shmem-rss:10132kB
Sep 16 12:39:10 ociopf-t-321.dmz kernel: remoteenforcerd invoked oom-killer: gfp_mask=0xd0, order=0, oom_score_adj=993
Sep 16 12:39:10 ociopf-t-321.dmz kernel: remoteenforcerd cpuset=docker-b45da1feed6df60107b15e61dacf3c661be48c9105d74133c7b54124c1087836.scope mems_allowed=0
```

Node RAM via "free"
```
# free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        9.9G        7.5G        190M         14G         20G
Swap:            0B          0B          0B
```
```
$ oc describe node ociopf-t-321.dmz
...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                        Requests       Limits
  --------                        --------       ------
  cpu                             6650m (83%)    41370m (517%)
  memory                          29720Mi (92%)  73256Mi (228%)
```

**Comment by wmhutchison** [comment]
@stewartshea Killed off one of the larger mem-using pods which caused the memory requests to drop to 70%-ish. Doing another node reboot on 321 to see if that'll clear things up.

**Comment by stewartshea** [comment]
Thx!
--
Shea Stewart, Partner
Arctiq: Intelligent Architecture
shea.stewart@arctiq.ca
+1-647-972-5191
http://www.arctiq.ca

**Comment by wmhutchison** [comment]
@stewartshea Reboot complete, leaving the node cordoned off for now. How does it look thus far? No oom messages yet.

**Comment by wmhutchison** [comment]
Process list looks a lot better too:

```
[root@ociopf-t-321 ~]# ps auxwww | grep enforce
root       5357  1.4  0.5 280396 178880 ?       Ssl  13:36   0:06 /enforcerd
root       8898  0.2  0.1 142056 34952 ?        Sl   13:38   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      14218  0.0  0.0   9092   932 pts/1    S+   13:44   0:00 grep --color=auto enforce
```

**Comment by brianonn** [comment]
Thanks @wmhutchison. We're also going to look into the possibility of decreasing the probability to have the oom killer choose the enforcerd process, since it an important part of the overall security solution. Other pods should be chosen before the enforcerd

**Comment by wmhutchison** [comment]
@brianonn @stewartshea I've now uncordoned the node, it's filled up again. Enforcer processes look stable too:

```
]# ps auxwww | grep enforce
root       5357  2.6  0.4 284320 137096 ?       Ssl  13:36   0:18 /enforcerd
root       8898  0.2  0.1 142056 34952 ?        Sl   13:38   0:01 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      23625  0.5  0.1 141872 39212 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      24084  0.5  0.1 141616 37456 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      24508  0.3  0.1 141452 35388 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      25998  0.4  0.1 141524 35908 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      26325  0.3  0.1 141688 35372 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      27306  0.4  0.1 141964 34920 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      27597  0.4  0.1 142220 37688 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      28411  0.4  0.1 141616 36968 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      28506  0.4  0.1 142036 37692 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      29203  0.4  0.1 140992 35408 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      29496  0.3  0.0 141524 32580 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      30131  0.4  0.1 141616 35436 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      30198  0.5  0.1 141872 35420 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      30442  0.5  0.1 141268 35644 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      30620  0.4  0.1 141432 35888 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      31296  0.5  0.1 141524 35888 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      31305  0.4  0.1 141688 34868 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      31488  0.4  0.1 141432 35420 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      31692  0.4  0.1 141780 37200 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      32562  0.4  0.1 141524 35672 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      32582  0.5  0.1 141340 35380 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      32804  0.6  0.1 141964 35124 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      32826  0.5  0.1 141340 35644 ?        Sl   13:46   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      34078  0.6  0.1 141524 33288 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      34092  0.6  0.1 141872 35884 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      34179  0.5  0.1 141432 35416 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      34186  0.5  0.1 141084 35416 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      35539  0.7  0.1 141872 32976 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      35545  0.7  0.0 141432 31312 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      35551  0.7  0.0 141524 32104 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      35555  0.7  0.0 141616 32900 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
root      36860  1.1  0.0 142220 29300 ?        Sl   13:47   0:00 /var/run/aporeto/tmp/bin/remoteenforcerd enforce
```

**Comment by stewartshea** [comment]
thanks for the update and help @wmhutchison

**Comment by stewartshea** [comment]
enforcers have appeared stable for the last day. closing this issue for now
